# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'restore package'
  inputs:
    command: 'restore'
    projects: 'CodeCoverage/After/CodeCoverage.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'building solution'
  inputs:
    command: 'build'
    projects: 'CodeCoverage/After/CodeCoverage.sln'

- task: DotNetCoreCLI@2
  displayName: 'running tests'
  inputs:
    command: 'test'
    projects: 'CodeCoverage/After/CodeCoverage.sln'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'CodeCoverage'

