# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'restore package'
  inputs:
    command: 'restore'
    projects: 'CodeCoverage/After/CodeCoverage.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'building solution'
  inputs:
    command: 'build'
    projects: 'CodeCoverage/After/CodeCoverage.sln'

- task: DotNetCoreCLI@2
  displayName: 'running tests'
  inputs:
    command: 'test'
    projects: 'CodeCoverage/After/CodeCoverage.sln'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: 'publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'CodeCoverage/After/CodeCoverage/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1  
  displayName: 'publish artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'CodeCoverage'

